#!/usr/local/bin/bash

export CONSUMER_KEY="17U7NC2dc1vWeK7iOdrfZw"
export CONSUMER_SECRET="dL2ULlFXO3gwXWpKamBFfYM4hTD6A0RBaoJW7sBg"

export ACCESS_TOKEN="789362959-jME1usiLXZbjtghfGsS9OgOXgqHslW3iXNGmTEc9"
export ACCESS_TOKEN_SECRET="6yKc5EGLgAf5zMT19iLnlXt3f8sXNWYWp3KEu94u1wNIy"

docker run -it -e CONSUMER_KEY=${CONSUMER_KEY} -e CONSUMER_SECRET=${CONSUMER_SECRET} \
-e ACCESS_TOKEN=${ACCESS_TOKEN} -e ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET} \
followfollowers.bot
